[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "confusionwords"
version = "0.0.1"
dependencies = ["regex", "numpy", "scipy"]

[tool.setuptools.package-data]
"confusionwords.data.da" = ['*.json']